name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout v3
        uses: "actions/checkout@v3"
      - name: hacs validation
        uses: "hacs/action@main"
        with:
          category: "appdaemon"
      - name: checkout v4
        uses: "actions/checkout@v4"
      - name: hassfest validation
        uses: "home-assistant/actions/hassfest@master"