name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  validate-hassfest:
    runs-on: "ubuntu-latest"
    steps:
        - names: checkout v4
        - uses: "actions/checkout@v4"
        - name: hassfest
        - uses: "home-assistant/actions/hassfest@master"